server:
  port: 8085
  servlet:
    context-path: /OrderDatabase

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/OrderDatabase
    username: root
    password: "@Luvanthanh24072005"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false


